framework:
  default_locale: 'fr' # Langue par défaut
  translator:
    default_path: '%kernel.project_dir%/translations' # Chemin vers les fichiers de traduction
    fallbacks:
      - 'en' # Langue de secours en cas de traduction manquante
      - 'fr' # Langue de secours supplémentaire
