controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_post:
    path: /post
    controller: App\Controller\PostController::index
show:
    path: /post/{slug}
    controller: App\Controller\PostController::show
    methods: ['GET','POST']
    requirements:
        slug: '[a-z0-9-]+'
